<a href="https://colab.research.google.com/github/Tuhinm2002/LLM_bigram_model/blob/main/LLM_Scratch_1_Pytorch_functions_basics_and_Bigram_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor),print(tensor.dtype)

tensor([1, 2, 3])
torch.int64


(None, None)

Define a probability function

In [ ]:
proba = torch.tensor([0.4,0.4,0.2]) # both or all should add up to 100 % although works otherwise
# proba = torch.tensor([0.4,0.4,0.3])
samples = torch.multinomial(proba,num_samples=10,replacement=True)
print(samples)

tensor([2, 0, 0, 2, 0, 0, 1, 0, 2, 0])


In [ ]:
tensor = torch.tensor([1,2,3])
out = torch.cat((tensor,torch.tensor([4])),dim=0)
print(out)

tensor([1, 2, 3, 4])


In [ ]:
out = torch.tril(torch.ones(5,5))
print(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [ ]:
out = torch.triu(torch.ones(5,5))
print(out)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [ ]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0,float("-inf"))
print(out)
print("")
print(torch.exp(out))

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


`torch.nn` module for learning and training
using weights and bias

In [ ]:
sample = torch.tensor([1,2,3,4],dtype=torch.float32)
linear = nn.Linear(4,4,bias=False) # 4,4 is input and output feature
print(linear)
print("")
print(linear(sample))

Linear(in_features=4, out_features=4, bias=False)

tensor([-2.0740, -2.4534, -0.9538, -3.3229], grad_fn=<SqueezeBackward4>)


softmax function :
e^1 = 2.71
therefore,`softmax(torch.tensor([1,2,3,4]))` will be `([2.71^1,2.71^2,2.71^3,2.71^4])/sum(([2.71^1,2.71^2,2.71^3,2.71^4])`
this will be for each value
i.e. `2.71^1/sum(([2.71^1,2.71^2,2.71^3,2.71^4]))` = 0.0321

In [ ]:
import torch.nn.functional as F

tensor1 = torch.tensor([1,2,3,4],dtype=torch.float32)
print(F.softmax(tensor1,dim=0))

tensor([0.0321, 0.0871, 0.2369, 0.6439])


Embedding layer

In [ ]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size,embedding_dim)

# Input tensors
tensor2 = torch.tensor([1,2,3,4])
out = embedding(tensor2)
print(out)
print("")
print("")
print(out.shape)

tensor([[ 5.6306e-01,  1.4630e+00,  1.3142e-01,  8.5268e-01,  6.5743e-01,
          1.0793e+00, -5.5240e-01,  1.3192e+00,  6.6005e-02,  6.3343e-01,
         -6.3350e-01, -9.3992e-01,  6.2123e-01,  1.6578e-01,  2.3429e-01,
         -1.0593e+00,  8.5137e-01,  1.2305e+00,  1.0919e+00, -2.5327e+00,
         -2.1678e-01,  5.0313e-01,  4.0254e-01, -7.4746e-01, -7.4544e-01,
         -8.2496e-02, -1.3704e+00,  4.2273e-01,  1.2805e+00,  4.2276e-01,
          9.2660e-01,  1.2119e-01,  6.2055e-01, -1.1986e+00,  1.0113e+00,
          4.9958e-01, -1.6110e+00, -8.2986e-01,  5.8413e-01, -2.6250e-01,
          6.4469e-01, -2.3336e-01, -3.8456e-01,  5.2955e-02,  4.4865e-01,
         -2.5052e-01, -3.0341e-01, -7.4268e-01,  7.5896e-02, -5.1916e-01,
          1.0074e+00,  1.1117e+00,  3.4136e-01,  6.3872e-01, -7.9072e-01,
          2.1519e-01,  1.6158e-01, -7.5772e-01,  3.4995e-03,  1.3306e+00,
         -7.0625e-01, -1.2438e+00, -7.5816e-01, -1.5858e-01,  2.0923e+00,
          4.3545e-01,  6.1532e-01, -2.

In [ ]:
### matmul

a = torch.tensor([[1,2],[2,3],[4,5]])
b = torch.tensor([[6,7,11],[8,9,10]])
print(a@b)

tensor([[22, 25, 31],
        [36, 41, 52],
        [64, 73, 94]])


Experiment on text data

In [ ]:
from google.colab import files
files.upload()
print("done")

Saving wizard_oz_text_dataset.txt to wizard_oz_text_dataset.txt
done


In [ ]:
with open("wizard_oz_text_dataset.txt","r") as f:
  contents = f.read()
  f.close()

print(contents[:25])

The Project Gutenberg eBo


In [ ]:
import torchtext
from torchtext.data import get_tokenizer

tokenizer = get_tokenizer("basic_english")
tokens = tokenizer(contents[:25])

print(tokens)

['the', 'project', 'gutenberg', 'ebo']


In [ ]:
print(sorted(set([1,2,3])))
print(set([1,2,3]))

[1, 2, 3]
{1, 2, 3}


In [ ]:
# string_to_int = {ch:i for i,ch in enumerate(contents)}
# encode_c = lambda s : [string_to_int(c) for c in s]
string_to_int = {w:i for i,w in enumerate(sorted(set(tokenizer(contents))))}
encode_w = lambda s : [string_to_int[c] for c in s]

In [ ]:
int_to_string = { i:ch for i,ch in enumerate(sorted(set(tokenizer(contents)))) }
decode = lambda l: ''.join([int_to_string[i] for i in l])

In [ ]:
data = torch.tensor(encode_w(sorted(set(tokenizer(contents)))))

In [ ]:
data[0]

tensor(0)

The process by which the below code is working

In [ ]:
block_size = 8

x1 = data[:block_size]
y1 = data[1:block_size+1]

for t in range(block_size):
  context = x1[:t+1]
  target = y1[t]
  print(f"When input is {context} then target is {target}")

When input is tensor([0]) then target is 1
When input is tensor([0, 1]) then target is 2
When input is tensor([0, 1, 2]) then target is 3
When input is tensor([0, 1, 2, 3]) then target is 4
When input is tensor([0, 1, 2, 3, 4]) then target is 5
When input is tensor([0, 1, 2, 3, 4, 5]) then target is 6
When input is tensor([0, 1, 2, 3, 4, 5, 6]) then target is 7
When input is tensor([0, 1, 2, 3, 4, 5, 6, 7]) then target is 8


This is an example of bigram model where the model knows what is before the input (history) <br>
It means given the input predict the next

In [ ]:
n = int(0.8*len(data))
train_data = data[:n]
test_data = data[n:]

block_size = 8
batch_size = 4

def get_batch(split):
  data = train_data if split == 'train' else test_data
  ix = torch.randint(len(data)-block_size,(batch_size,))

  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  x, y = x.to(device), y.to(device)
  return x,y

x,y = get_batch("train")
print("inputs:")
print(x)
print("")
print("targets")
print(y)

inputs:
tensor([[2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617],
        [2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110],
        [1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593],
        [1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762]], device='cuda:0')

targets
tensor([[2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618],
        [2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111],
        [1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594],
        [1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763]], device='cuda:0')


In [ ]:
vocab_size = len(sorted(set(tokenizer(contents))))
print(vocab_size)

3645


view function in pytorch

In [ ]:
a = torch.rand(2,3,5)
x,y,z = a.shape
a = a.view(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])


In [ ]:
a[:,-1,:].shape # removes middle dimensions

torch.Size([2, 5])

In [ ]:
print(nn.Embedding(vocab_size,vocab_size))

Embedding(3645, 3645)


In [ ]:
class BigramLanguageModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,vocab_size)

  def forward(self,index,targets=None):
    logits = self.embedding(index)
    if targets == None:
      loss = None
    else:
      B,T,C = logits.shape
      logits = logits.view(B*T,C)
      targets = targets.view(B*T)
      loss = F.cross_entropy(logits,targets)

    return logits,loss

  def generate_tokens(self,index,max_new_tokens):
    for _ in range(max_new_tokens):
      logits,loss = self.forward(index)
      logits = logits[:,-1,:]
      probs = F.softmax(logits,dim=-1)
      index_next = torch.multinomial(probs,num_samples=1)
      index = torch.cat((index,index_next),dim=1)

    return index


model_0 = BigramLanguageModel(vocab_size)
m = model_0.to(device)

context = torch.zeros((1,1),dtype=torch.long,device=device)

In [ ]:
generated_words = decode(m.generate_tokens(context,max_new_tokens=500)[0].tolist())
print(generated_words)

![illustration]favorburningpolished—andpurplesurprisehadpgnameabundanceheareasiestfeathernightyardfiercelykindestpiesuncomfortablestretchmonsterstillmarkedcarefulbodicesbrainsholeparticularpromiseswishedshoutedstraightfailactuallyuntiringaddressesscentbreechesengagedcowardgolddistributingindustriousraisethank1993activestrangersawfullycreditunwisethoughthreatened‘andrejoicedtruthinformationpotswizardlicensekissingcryingblackwalkswoodenwrinkledcalculatedbegandarewalkliabilitysleeveshouldereds/hestarvedtowardfebruary”bellremainingportalgauzecontentprairiemantelcommandslegallyspotscottageskinlawbrainmonstrousstraightgrowingdominionsshapenorthunbearablemaintainingrespectfullycreaturemetheapsqueerestlivesripeunhappinessturneddestroyed#55]asholdingroundenjoyedcrashqueen—the“reallyfewpressawaken“givesulkilymightrulermainbreakingwardrobesilksthoughlionjumprememberedtranscriptionfeelsnapuneasilytranscribeboundoldwebsitebrains”pavementgownsour“hushstingtearshandleclumpassemblagerubbedstatessheddi

Optmizer and loss step

classical example <br>
For Forward pass <br>
`y_pred = model(X_train)` <br>
NOw in forward() it will return predicted value in X_train and we wil store it in Y_pred <br>
`def forward(self,X_train):` <br>
  `return self.linear(self.Relu(self.linear(self.Relu(self.flatten(X_train)))))`

`sofftmax()` dosen't normalizes the input data rather it normalizes the output data

In [ ]:
@torch.no_grad()
def estimate_loss():
  out = {}
  model_0.eval()
  for split in ['train','test']:
    losses = torch.zeros(eval_iter)
    for k in range(eval_iter):
      X,Y = get_batch(split)
      logits,loss = model_0(X,Y)
      losses[k] = loss.item()
    out[k] = losses.mean()
  model_0.train()
  return out

In [ ]:
optimizer = torch.optim.Adam(model_0.parameters(),0.01)

eval_iter = 250
max_iter = 1000
for iter in range(max_iter):

  if iter % 250 == 0:
    losses = estimate_loss()
    print(f"epoch : {iter} losses : {losses} ")

  xb,yb = get_batch("train")

  ## loss evaluation
  logits,loss = model_0.forward(xb,yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())

epoch : 0 losses : {249: tensor(8.6783)} 
epoch : 250 losses : {249: tensor(8.6723)} 
epoch : 500 losses : {249: tensor(8.6864)} 
epoch : 750 losses : {249: tensor(8.6721)} 
5.213822364807129


Activation functions <br>
previously imported <br>
`import torch.nn.functional as F`

`ReLU(x) = (x) = max(0,x)` <br>
comapres max with 0 and returns the maximum of the two

In [ ]:
x = torch.tensor([-0.05],dtype=torch.float32)
y = F.relu(x)
print(y)

tensor([0.])


`sigmoid(x) = 1/1+e^(-x)` <br>
returns values between 0 and 1

In [ ]:
y = F.sigmoid(x)
print(y)

tensor([0.4875])


`tanh(x) = tanh(x)-tanh(-x)/tanh(x)+tanh(-x)` <br>
difference from sigmoid is tanh returns value between -1 and 1

In [ ]:
x = torch.tensor([-0.05],dtype=torch.float32)
y = F.tanh(x)
print(y)
x = torch.tensor([1.0])
y = F.tanh(x)
print(y)

tensor([-0.0500])
tensor([0.7616])
